import { Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { InjectDataSource } from '@nestjs/typeorm';
import { createHmac } from 'crypto';
import { DataSource } from 'typeorm';

export interface AuthenticatedUser {
  id: string;
  tier: string;
  locale: string;
  timezone: string;
}

export interface JwtPayload {
  sub: string;
  tier: string;
}

@Injectable()
export class AuthService {
  constructor(
    @InjectDataSource() private readonly dataSource: DataSource,
    private readonly jwt: JwtService,
    private readonly config: ConfigService,
  ) {}

  /**
   * Device identifiers are stored as a keyed hash, never in the clear.
   *
   * The identifier is generated by the app and is stable for the lifetime of an
   * install, which makes it a tracking identifier. Keying the hash with the
   * server secret means a database copy on its own cannot be correlated back to
   * a device, while lookup still works because the same input always produces
   * the same digest.
   */
  private hashDeviceId(deviceId: string): string {
    const secret = this.config.get<string>('auth.jwtSecret') ?? '';
    return createHmac('sha256', secret).update(deviceId.trim()).digest('hex');
  }

  /**
   * Signs in an anonymous device, creating the account on first contact.
   *
   * This is the whole account model for the MVP. Google sign-in is unreliable
   * inside Iran and SMS OTP is meaningless to a visitor abroad, so neither can
   * be the entry point. A device account works everywhere with no sign-up, and
   * auth_identities is already in place for linking a real identity later.
   */
  async authenticateDevice(input: {
    deviceId: string;
    locale?: string;
    timezone?: string;
  }): Promise<{ accessToken: string; user: AuthenticatedUser }> {
    const deviceHash = this.hashDeviceId(input.deviceId);

    const [user] = await this.dataSource.query(
      `INSERT INTO users (anonymous_device_id, locale, timezone, last_seen_at)
       VALUES ($1, COALESCE($2, 'fa'), COALESCE($3, 'Asia/Tehran'), now())
       ON CONFLICT (anonymous_device_id) DO UPDATE
         SET last_seen_at = now(),
             locale   = COALESCE($2, users.locale),
             timezone = COALESCE($3, users.timezone)
       RETURNING id, tier::text AS tier, locale, timezone`,
      [deviceHash, input.locale ?? null, input.timezone ?? null],
    );

    return { accessToken: await this.issueToken(user), user };
  }

  private async issueToken(user: AuthenticatedUser): Promise<string> {
    const payload: JwtPayload = { sub: user.id, tier: user.tier };
    const expiresIn = this.config.get<string>('auth.jwtExpiresIn', '90d');

    return this.jwt.signAsync(payload, {
      secret: this.config.get<string>('auth.jwtSecret'),
      // jsonwebtoken types expiresIn as a narrow template literal union, which
      // a value read from the environment cannot satisfy at compile time. The
      // format is validated by the library at runtime.
      expiresIn: expiresIn as unknown as number,
    });
  }

  async verify(token: string): Promise<AuthenticatedUser> {
    let payload: JwtPayload;
    try {
      payload = await this.jwt.verifyAsync<JwtPayload>(token, {
        secret: this.config.get<string>('auth.jwtSecret'),
      });
    } catch {
      throw new UnauthorizedException('invalid or expired token');
    }

    // The token is not trusted on its own: a deactivated account must stop
    // working before its long-lived token expires.
    const [user] = await this.dataSource.query(
      `SELECT id, tier::text AS tier, locale, timezone
       FROM users WHERE id = $1 AND is_active`,
      [payload.sub],
    );
    if (!user) throw new UnauthorizedException('account is no longer active');

    return user;
  }

  async touch(userId: string): Promise<void> {
    await this.dataSource.query(`UPDATE users SET last_seen_at = now() WHERE id = $1`, [userId]);
  }
}
